application: keylookup-hrd
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /key/([0-9A-F]+)
  script: keylookup.app
  secure: always
- url: /cron/0mirror
  script: cron.app
  login: admin

includes:
- 0mirror-update.cap
